services:
  config-svr-1:
    image: mongo:latest
    container_name: config-svr-1
    ports:
      - "27101:27018"
    command: mongod --configsvr --replSet config-svr-replica-set --port 27018
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/config-svr-1-data:/data/db

  config-svr-2:
    image: mongo:latest
    container_name: config-svr-2
    ports:
      - "27102:27018"
    command: mongod --configsvr --replSet config-svr-replica-set --port 27018
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/config-svr-2-data:/data/db

  config-svr-3:
    image: mongo:latest
    container_name: config-svr-3
    ports:
      - "27103:27018"
    command: mongod --configsvr --replSet config-svr-replica-set --port 27018
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/config-svr-3-data:/data/db

  shard-1-node-a:
    image: mongo:latest
    container_name: shard-1-node-a
    ports:
      - "27111:27019"
    command: mongod --shardsvr --replSet shard-1-replica-set --port 27019
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/shard-1-node-a-data:/data/db

  shard-1-node-b:
    image: mongo:latest
    container_name: shard-1-node-b
    ports:
      - "27112:27019"
    command: mongod --shardsvr --replSet shard-1-replica-set --port 27019
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/shard-1-node-b-data:/data/db

  shard-1-node-c:
    image: mongo:latest
    container_name: shard-1-node-c
    ports:
      - "27113:27019"
    command: mongod --shardsvr --replSet shard-1-replica-set --port 27019
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/shard-1-node-c-data:/data/db

  shard-2-node-a:
    image: mongo:latest
    container_name: shard-2-node-a
    ports:
      - "27121:27019"
    command: mongod --shardsvr --replSet shard-2-replica-set --port 27019
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/shard-2-node-a-data:/data/db

  shard-2-node-b:
    image: mongo:latest
    container_name: shard-2-node-b
    ports:
      - "27122:27019"
    command: mongod --shardsvr --replSet shard-2-replica-set --port 27019
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/shard-2-node-b-data:/data/db

  shard-2-node-c:
    image: mongo:latest
    container_name: shard-2-node-c
    ports:
      - "27123:27019"
    command: mongod --shardsvr --replSet shard-2-replica-set --port 27019
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/shard-2-node-c-data:/data/db

  shard-3-node-a:
    image: mongo:latest
    container_name: shard-3-node-a
    ports:
      - "27131:27019"
    command: mongod --shardsvr --replSet shard-3-replica-set --port 27019
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/shard-3-node-a-data:/data/db

  shard-3-node-b:
    image: mongo:latest
    container_name: shard-3-node-b
    ports:
      - "27132:27019"
    command: mongod --shardsvr --replSet shard-3-replica-set --port 27019
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/shard-3-node-b-data:/data/db

  shard-3-node-c:
    image: mongo:latest
    container_name: shard-3-node-c
    ports:
      - "27133:27019"
    command: mongod --shardsvr --replSet shard-3-replica-set --port 27019
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/shard-3-node-c-data:/data/db

  router:
    image: mongo:latest
    container_name: router
    ports:
      - "27141:27020"
    command: mongos --configdb config-svr-replica-set/config-svr-1:27018,config-svr-2:27018,config-svr-3:27018 --port 27020 --bind_ip_all
    networks:
      - mongo-shard-cluster
    volumes:
      - /mnt/MongoDB/router-data:/data/db

networks:
  mongo-shard-cluster:
    driver: bridge
    name: mongo-shard-cluster

